### ISSUE TITLE
change subtitle source

### ISSUE THREAD

**Issue by amitez** [Diblo/KODI-Popcorn-Time#11]
hi diblo,whatsup?

your code is great,i love it,i want to ask you how can change the subtitle source instead of yify subtitle?

the hebrew subs is not great there .

thanks,amit.

**Comment by Diblo** [comment]
It is not possible right now, but I'm working to make it possible to select alternative subtitle provider. Until then it is possible to use XBMC / KODI player to find your subtitles.

**Comment by amitez** [comment]
hi henrik, thanks for your quick response, i will use the second option
until there is alternative, thanks again, amit.
בתאריך 25 ביוני 2015 20:22,‏ "Henrik Ankersø" <notifications@github.com>
כתב:

**Comment by Diblo** [comment]
This future have been added in version 0.7.0, although we wait on three-parties to write providers.
