### ISSUE TITLE
Multilanguage Addon

### ISSUE THREAD

**Issue by cabrote** [Diblo/KODI-Popcorn-Time#14]
Please translate to Spanish. I can help if you like

**Comment by Diblo** [comment]
hi cabrote
You are very welcome to help, but it will not be possible before the next release, as xbmctorrent not supported full translation. (It's part of the rewriting progress)

Greetings
Diblo

**Comment by Diblo** [comment]
Hey @cabrote 
If you still want to translate to Spanish, there is information about it here:  https://github.com/Diblo/KODI-Popcorn-Time/blob/master/HELP_WANTED.md

Many thanks in advance.

**Comment by Diblo** [comment]
Add with commit: https://github.com/Diblo/KODI-Popcorn-Time/commit/bb1014bd430bfff2cab5000e1f8a3ab0590dd7ff
