### ISSUE TITLE
android_x86 support

### ISSUE THREAD

**Issue by liotcheg** [Diblo/KODI-Popcorn-Time#15]
Thanks you for this great addon.
Do you plan android_x86 support?
kodi.log: 18:54:12 T:1907591472  NOTICE: IOError: [Errno 2] No such file or directory: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kodipopcorntime/resources/bin/android_x86/torrent2http'

**Comment by Diblo** [comment]
Hi
Thank you for your feedback.
I think it's a mistake. I will look at it :)

Greetings
Diblo

**Comment by liotcheg** [comment]
Thanks!
JFYI, https://github.com/anteo/script.module.torrent2http says that precompiled binaries are available only for Android ARM. 
Maybe it can be easily compiled?

**Comment by Diblo** [comment]
The problem is that it is a very different Torrent file and it requires player.py being rewritten. However, the new release will use Anteo version of torrent2http.
#7

**Comment by chakhdin** [comment]
I believe the problem with Android x86 support in torrent2http depends on inability of Golang (language used to develop torrent2http) to target that platform. https://github.com/golang/go/issues/9327 sums up the state of Android x86 support in Golang

**Comment by Diblo** [comment]
Yah this is a golang problem.
