### ISSUE TITLE
Script Failed

### ISSUE THREAD

**Issue by gregpa** [Diblo/KODI-Popcorn-Time#17]
Loaded with the most recent release of the repository and add-on.  I get the movie listing,  but it has a script failed issue. the movie tries to buffer, but ultimately fails.
-- correction.  All seems to be well after update to Kodi 15

**Comment by Diblo** [comment]
Hello @gregpa 
Thank you for created an error report.
Can you post or link to your kodi.log file? - [Easy Log file guide.](http://kodi.wiki/view/Log_file/Easy)
If you have more questions on how you post your log file, please feel free to ask.

**Comment by Diblo** [comment]
This is a duplicate of https://github.com/Diblo/KODI-Popcorn-Time/issues/16

**Comment by cunca1975** [comment]
i have the same problem
