### ISSUE TITLE
Couple of things

### ISSUE THREAD

**Issue by gripped** [Diblo/KODI-Popcorn-Time#18]
In readme.md

Supported Platforms
Linux x32 and x64

It worked out of the box on Linux ARM (odroid XU3 Kodi 15.1rc) so maybe you could add Linux arm to the list of supported platforms ? Some people might not even try it.

In the instructions for the Alpha (0.7.0) I'm told to simply include the source code from https://github.com/anteo/torrent2http into the bin folder.

This did not work on arm. It complained about a missing binary
`13:18:03 T:2488652464   ERROR: [plugin.video.kodipopcorntime] Can't find torrent2http binary for linux/arm`

Copying the binaries from https://github.com/anteo/xbmc.repository/blob/master/script.module.torrent2http/script.module.torrent2http-0.0.7.zip did work.

Thanks for the add-on

**Comment by Diblo** [comment]
Hi gripped
Thank you for your feedback.
I will correct both description :)

Greetings
Diblo
