### ISSUE TITLE
Does not work w/ SOCKS5 Proxy

### ISSUE THREAD

**Issue by smromain** [Diblo/KODI-Popcorn-Time#19]
Have been attempting to use the plugin using a SOCKS 5 proxy, which has been set on global settings.

Seems like the torrent2http module has been throwing errors, when the file is attempting to be accessed. Any way to ensure that torrent2http bypasses the proxy?

**Comment by Diblo** [comment]
Hi smromain
Thank you for your feedback.
It's not something I know about. torrent2http is outside my area because it is a 3 party software. But I will add it to the list of enhancements.

Greetings
Diblo

**Comment by Diblo** [comment]
I have just released Alpha version 2 - You can downloade it from her: https://github.com/Diblo/KODI-Popcorn-Time/wiki/Test-releases#test-alpha-version-070

See if this works - Remember to read the note.
