### ISSUE TITLE
Language resource file

### ISSUE THREAD

**Issue by JKetelaar** [Diblo/KODI-Popcorn-Time#21]
String id 30132 and string id 30148 are exactly the same.
```
  <string id="30132">Port</string>
  <string id="30148">Port</string>
```

Figured it while I was translating the resource file to Dutch!

**Comment by Diblo** [comment]
Thanks :+1:

**Comment by JKetelaar** [comment]
Also @Diblo - As said in another pull request, I haven't translated it to German but to Dutch. I'll do German later today.

**Comment by Diblo** [comment]
Yes, I noticed :)
