### ISSUE TITLE
Can't install repository

### ISSUE THREAD

**Issue by MrHaroldA** [Diblo/KODI-Popcorn-Time#25]
Kodi 14 complains about the zip not having the correct format / information.

Steps to reproduce:
* Download https://github.com/Diblo/KODI-Popcorn-Time/archive/1.0.3.zip
* Copy it to your Kodi machine
* Install by going to System > Add ons > install from zip
* Wait a few seconds
* The error appears in the bottom right corner

Kodi Popcorn Time itself installed just fine, but I like it to updated automatically ;)

**Comment by Diblo** [comment]
I have made a nye release :+1:

**Comment by MrHaroldA** [comment]
Install went fine now! Unfortunately, there's my ISP's DNS servers are failing (again), so refreshing the repository doesn't wirk at the moment.

But the installer is fixed ;)

**Comment by Diblo** [comment]
:+1:
