### ISSUE TITLE
Filter results

### ISSUE THREAD

**Issue by krantzet** [Diblo/KODI-Popcorn-Time#27]
I would very much like to be able to show only 720p, 1080p or 3D.
I cant find any settings for that - so every movie shows up 2-3 times in the list with different resolution. Would be a great improvment if you could hide the resolutions you dont want to see.

**Comment by Diblo** [comment]
I have already built this in version 0.7.0 alpha.
I have added the "Preferred Quality" setting where there is a choice between "Only 720p," "Only 1080p" and "1080p and lower" and "Play of 3D video" where there is a choice between "Never", "Ask me" and "Always."
\- and movies appears only once. :)
