### ISSUE TITLE
Cant install repository on openelec 5.95.4

### ISSUE THREAD

**Issue by maximm07** [Diblo/KODI-Popcorn-Time#29]
It worked on previous version..but failing to install in latest version...

here is log file:

10:07:46 516.107239 T:1768944704  NOTICE: Thread JobWorker start, auto delete: true
10:07:53 522.880210:07:53 522.884460 T:1768944704   ERROR: CAddonInstallJob[repository.kodipopcorntime]: could not read addon desc                  ription of special://home/addons/repository.kodipopcorntime
10:07:53 522.990051 T:1750070336  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by maximm07** [comment]
sorry fix it..it was /storage full problem.

**Comment by Diblo** [comment]
:+1:
