### ISSUE TITLE
Dependencies  not met

### ISSUE THREAD

**Issue by Kalikazoo** [Diblo/KODI-Popcorn-Time#3]
Android tablet, Kitkat 4.4.2., Gotham 13.2
Dependencies not met error when installing from zip file.
If I unpack the zip file and install manually to the addons
folder in XBMC/Kodi, addon works fine.
Thanks for the addon and your time creating it.

**Comment by Diblo** [comment]
Hello Kalikazoo
Thanks for the feedback. I am happy to hear that it works for you.
The reason to the dependency error is that KODI Popcorn Time have only been tested on KODI Helix 14.x platform. The add-on have therefore a minimum requirements at 2.19.0.
- However, I will make a pre-release that will aims against Gotham, who can be be tested.

Henrik

**Comment by Diblo** [comment]
[KODI Popcorn Time (Gotham) 0.6.3 beta ](https://github.com/Diblo/KODI-Popcorn-Time/releases/tag/0.6.3-beta)

**Comment by arzaz** [comment]
Dear Diblo,

May i have the repo to install the beta version for Gotham?

**Comment by Diblo** [comment]
Hey, you shall download the zip file from here [KODI Popcorn Time (Gotham) 0.6.3 beta ](https://github.com/Diblo/KODI-Popcorn-Time/releases/tag/0.6.3-beta), and goto add-ons in settings an hit install add-ons from zip file
