### ISSUE TITLE
Alpha-problem

### ISSUE THREAD

**Issue by krantzet** [Diblo/KODI-Popcorn-Time#31]
When I try to run the alpha everything works great up until http2torrent get called up. I get an "OS not supported". 

I have downloaded the http2torrent-zip and placed the win7x64-files into the bin folder and Made a new zip-filé, installerad it successfully and verified that I am actually rundning 0.7alpha. Is there anything else i need to configure?

**Comment by Diblo** [comment]
Hello @krantzet
It could seem that it is a bug. What operating system are you using?

Diblo

**Comment by Diblo** [comment]
Well, just forget about my first message.
You must keep the folder "***windows_x64***" when unpacking the file.

    [...]bin\windows_x64\torrent2http.exe
    [...]bin\windows_x64\libtorrent-go.dll

**Comment by krantzet** [comment]
Thanks! Now it works
