### ISSUE TITLE
Search not workin in .70 Alpha

### ISSUE THREAD

**Issue by chakhdin** [Diblo/KODI-Popcorn-Time#33]
Hi, the following error is visible in the Kodi (15.1) log file when I enter a search string:
01:54:51 T:30964  NOTICE: Thread LanguageInvoker start, auto delete: false
01:54:51 T:30964  NOTICE: -->Python Interpreter Initialized<--
01:54:51 T:30964  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
01:54:51 T:30964  NOTICE: [xbmcswift2] Request for "/catalogs" matches rule for function "catalogs"
01:54:51 T:32800  NOTICE: Thread BackgroundLoader start, auto delete: false
01:54:52 T:22416  NOTICE: Thread LanguageInvoker start, auto delete: false
01:54:52 T:22416  NOTICE: -->Python Interpreter Initialized<--
01:54:52 T:22416  NOTICE: [xbmcswift2] Request for "/search" matches rule for function "search"
01:54:54 T:22416   ERROR: [plugin.video.kodipopcorntime] An unknown error has occurred
01:54:54 T:22416   ERROR: [plugin.video.kodipopcorntime] Traceback (most recent call last):
01:54:54 T:22416   ERROR: [plugin.video.kodipopcorntime]   File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.kodipopcorntime\addon.py", line 231, in search
01:54:54 T:22416   ERROR: [plugin.video.kodipopcorntime]     plugin.redirect(plugin.url_for(item.pop('endpoint'), **_get_kwargs({'query': query, 'page': 1})[0]))
01:54:54 T:22416   ERROR: [plugin.video.kodipopcorntime] NameError: global name 'item' is not defined
01:54:54 T:30952   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kodipopcorntime/search?_pickled=qualities&limit=20&provider=movie_yify&qualities=(lp1%0aS%27720p%27%0ap2%0aaS%271080p%27%0ap3%0aa.
01:54:54 T:30952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kodipopcorntime/search?_pickled=qualities&limit=20&provider=movie_yify&qualities=(lp1%0aS%27720p%27%0ap2%0aaS%271080p%27%0ap3%0aa.) failed
01:54:54 T:32092  NOTICE: Thread LanguageInvoker start, auto delete: false
01:54:54 T:32092  NOTICE: -->Python Interpreter Initialized<--
01:54:54 T:32092  NOTICE: [xbmcswift2] Request for "/" matches rule for function "index"
01:54:54 T:32092  NOTICE: [xbmcswift2] Request for "/catalogs" matches rule for function "catalogs"
01:54:54 T:33544  NOTICE: Thread BackgroundLoader start, auto delete: false

I guess all that part is still WIP.

**Comment by Diblo** [comment]
Hello @chakhdin 
Thank you for your bug report. I have correct the source code :)
\- I would like to point out that the alpha version is not able to perform a search query.
