### ISSUE TITLE
Non-stereo movies?

### ISSUE THREAD

**Issue by elvijsuntals** [Diblo/KODI-Popcorn-Time#40]
Hi! Thanks for this project!

I have trouble with all the movies on here, as it seems they are all in stereo? Is it possible to get DTS-encoded movies with kodi-pocorntime?

**Comment by chakhdin** [comment]
The movies available through this plugin are the ones listed on http://yts.to
Check with those guys for the movies and quality/sound options you like.
The plugin is merely a way to get those movies on your Kodi

**Comment by elvijsuntals** [comment]
Ok, thanks for clarification. Is there a way to change the provider then? I'd really love this on my Kodi, but the quality is too low. 





--

**Comment by chakhdin** [comment]
I believe that's how Popcorn Time works. And the plugin replicates that behavior.

Cheers
