### ISSUE TITLE
Please improve yts url option

### ISSUE THREAD

**Issue by riartem** [Diblo/KODI-Popcorn-Time#47]
In the advanced settings we can set custom url for YTS catalog. But only the domain.
Please, improve this setting to make ability use custom YTS paths.
For example, YTS with russian translated films is: http://api.popcorn-time.ru/yts/ (work uri http://api.popcorn-time.ru/yts/list_movies.json) and now I can not config Kodi-Popcorn-Time to work with that catalog.

Thank you very much for great work!

**Comment by Diblo** [comment]
Add ind commit: https://github.com/Diblo/KODI-Popcorn-Time/commit/7649f811e68fc436f4b050237a2752755e264c13
