### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by tomcontr** [Diblo/KODI-Popcorn-Time#48]
Hi, 
There is a lot content that I can se in the real Popcorn TIme App but I cant find it here.
Is there any way that I could add more movies?

Best Regards

**Comment by Frepke** [comment]
+1 Yes, same problem for me :(

**Comment by chakhdin** [comment]
Could you provide a couple of examples for the missing content?

**Comment by Frepke** [comment]
Jurassic World

**Comment by Frepke** [comment]
Last week the Harry Potters were missing (not anymore)

**Comment by chakhdin** [comment]
The source for the available movies for the plugin is http://yts.to Please check if the missing content is available there. 

Cheers

**Comment by Frepke** [comment]
Hmmm, movies are missing there too.
Can't we use the same source as the original popcorn time?

**Comment by hejman** [comment]
Jurassic World is not available on Popcorn Time - i just checked.

Popcorn Time is also using the YTS API - so it should be similar.

**Comment by Frepke** [comment]
Strange, it's available in my version of PopcornTime.

![capturfiles-sep -22-2015_17 01 18](https://cloud.githubusercontent.com/assets/6153559/10022196/d74f13fa-614b-11e5-9f51-2868026b7d95.jpg)

kr.,
Patrick

**Comment by chakhdin** [comment]
Not on mine:
![jurassic](https://cloud.githubusercontent.com/assets/13959311/10022852/3b20c574-614f-11e5-8e0f-efb68ced17a2.png)

**Comment by Frepke** [comment]
My screen dump is from the original PopcornTime.

kr.,
Frepke

**Comment by hejman** [comment]
There are two (or more) versions of PopcornTime, very confusing. 

the .se and the .io version. I know for a fact that the .io version uses yts api and thus should list the same movies.

Im unsure about the .se version - but Jurassic World is not available on YTS which explains this.

**Comment by Diblo** [comment]
@Frepke 
We can try to see what the difference is. But we can not promise anything specific at present, and not even after the release of version 0.7.0.

You must have a big thank for making us aware of the difference and even though I violated it sounded noticeably strange.

I am of course sorry that we can not promise more. However, I hope that you can still use KODI Popcorn Time in the future.

**Comment by Frepke** [comment]
Of course im very thankful for all the work you do to make such a wonderful program.
I love it and it works great. If it's possible I try to help to make it even better, but unfortunately my help is limited to give information about things I notice.

Thanks for PopcornTime
Frepke

**Comment by thetruemachine** [comment]
To My appears me 
![captura de pantalla 20](https://cloud.githubusercontent.com/assets/14945841/10255701/18b0a914-691a-11e5-8ae8-d508fad45efa.png)

**Comment by thetruemachine** [comment]
changes http://yts.to by http://yts.pw

**Comment by Frepke** [comment]
Thanx thetruemachine,

Gonna try it.

**Comment by thetruemachine** [comment]
forgiveness address is http://ytsproxy.pw

**Comment by Frepke** [comment]
Thanx again

**Comment by chakhdin** [comment]
Just to let you know, guys, that Jurassic World is available on yts.to now, too; it was not at the time of report. So, no need to change the domain to have it available.

Cheers
