### ISSUE TITLE
iMac 

### ISSUE THREAD

**Issue by mandrake2020** [Diblo/KODI-Popcorn-Time#5]
Installed on IMac and no seeds ay all.Opened firewall and still not getting any I appreciate any help,tks

**Comment by Diblo** [comment]
Hi @mandrake2020 

I have released Alpha version 2 and it may help us to fix this problem. Can you try to install this version from [here](https://github.com/Diblo/KODI-Popcorn-Time/wiki/Test-releases#download-1) and report back. (Remember to read the note)

\- If that does not work, we have far better log information in this version. You just need to, turn on the system and add-on debugging. Then post the log after having recreated the error. - [Easy Log file guide.](http://kodi.wiki/view/Log_file/Easy)

![kodi_popcorn_time_-_settings_advanced_1 1](https://cloud.githubusercontent.com/assets/11947723/10190432/ce342536-676c-11e5-8130-adee6e8ecb7b.jpg)
