### ISSUE TITLE
Popcorn Time 0.6.5 'unable to connect' on Kodi 15.1

### ISSUE THREAD

**Issue by zappan** [Diblo/KODI-Popcorn-Time#55]
Hey guys,

I have an issue - just upgraded Kodi to v15.1 on my MyGica ATV582 device, and installed Popcorn Time 0.6.5 (tried installations from both, SuperRepo, and Popcorn Time repo). When I search the movies, I get an error message 'Unable to connect to yfs.to'.

Here's the debug log:
http://xbmclogs.com/ppip2vk3p

It worked okay with Kodi v14 just before I did the upgrade (not sure which Popcorn time version it was running on that, I don't have it recorded). Anything that I'm missing after the upgrade?

**Comment by zappan** [comment]
Uhhh, there was some network routing issue.
All fine now.
Closing this as invalid.

**Comment by voveson** [comment]
Would you mind sharing how you resolved this?

**Comment by zappan** [comment]
It was a network issue, when my ISP got their stuff sorted out, it was all OK
