### ISSUE TITLE
If no subtitle language was ever chosen movie playback fails in 0.70 Alpha 2

### ISSUE THREAD

**Issue by chakhdin** [Diblo/KODI-Popcorn-Time#56]
AttributeError: type object 'Loader' has no attribute 'subtitle': http://goo.gl/fTBfdQ

**Comment by Diblo** [comment]
Hi @chakhdin 
I have corrected the error. - Do you have a google account?

**Comment by Diblo** [comment]
[KODI Popcorn Time 0.7.0~alpha2.zip](https://drive.google.com/file/d/0B3fNnjj64nUpdDN3WXBFdDZEd0U/view?usp=sharing)
