### ISSUE TITLE
Alpha 2: "Opening stream" dialog open after playback starts

### ISSUE THREAD

**Issue by chakhdin** [Diblo/KODI-Popcorn-Time#57]
This happens only if instead of pressing "P" (Play) on the movie directly, you press "Enter" and then press  "Play" button in the movie details window. Logs: http://goo.gl/TIVBGu
![image](https://cloud.githubusercontent.com/assets/13959311/10142903/c0820d02-6615-11e5-9cf5-c05b56ea77c4.png)
![image](https://cloud.githubusercontent.com/assets/13959311/10142914/ca5397f6-6615-11e5-9739-a39ad93c0d07.png)

**Comment by Diblo** [comment]
I know the error, but it can not be the same mistake ... so why does it do that.
* What happens if you right-click and press play?
* What happens if you set KODI to "choose" isted for "Show information" as standard action? ("choose", "play", etc.)
![screenshot001](https://cloud.githubusercontent.com/assets/11947723/10144685/28cb987a-661f-11e5-9b43-cf0bc2e2f42d.jpg)

**Comment by Diblo** [comment]
Working play action:
* Shortcut: "P"
* Default select action: "Play"
* Default select action: "Choose" -> "Play"

Play action which crashes KODI:
* Shortcut: "I" -> "Play"
* Default select action: "Show information" -> "Play"
* Default select action: "Choose" -> "Show information" -> "Play"

Play action that do nothing:
* Default select action: "Resume"

**Comment by chakhdin** [comment]
I'm having hard time testing this because I started having weird freezes after the movie started playback. Also, right clicking in the movie information window avoids the "Opening stream" dialog, but then Kodi won't work regularly, I wouldn't be able to enter in any add-on and some more strange stuff. I have to exit Kodi (sometimes kill it).
I also noticed that torrent2http is not stopped after I stop playback. Is this normal?

I will report back if I'm able to test your cases again.

EDIT: oops. You posted another comment. 
I can confirm that any play action from Information Page results in strange behavior (Opening stream dialog, Kodi behaving weirdly after stopping the playback and so on). Playing from movie list has no problems

**Comment by Diblo** [comment]
For torrent2http. Yes and no, it stops almost to all circumstances.

I have found 3 ways it does not.
1. On a Windows machine. If you are close KODI from the desktop. eg. right click at the icon at the progress bar and choose close
2. If KODI freezes
3. If the `Loader` in `torrent.py` fails. (This should not happen but it did when I look a you last report)

\- With regard to Windows I am looking at [`xbmc.Monitor`](http://romanvm.github.io/xbmcstubs/docs/xbmc.Monitor-class.html) to see if it can help us.

**Comment by Diblo** [comment]
The error is in line 578 `XFILE::CPluginDirectory::StartScript - calling plugin KODI Popcorn Time('plugin://plugin.video.kodipopcorntime/','2','?action=seeds&endpoint=browse&mediaType=movies')`
It is not documented anywhere, but when we use `xbmc.player()` the handle id must be -1 (not 2). (-1 means that we do not have a handle id)
Eg. if we use `xbmcplugin.setresolvedurl()` to play the stream then we need a handle id. This is achieved by adding "isPlayable" to item info.
But why view information does not follow the item info is a mystery to me.

**Comment by Diblo** [comment]
http://trac.kodi.tv/ticket/16290

**Comment by Diblo** [comment]
http://trac.kodi.tv/ticket/10380
http://trac.xbmc.org/ticket/14192

**Comment by chakhdin** [comment]
You're not investigating the xbmcplugin.setresolvedurl() solution?

**Comment by Diblo** [comment]
Yes there is nothing else to do ... I come with a new update in 20 minutes

**Comment by Diblo** [comment]
\- I have update the zip file.

**Comment by Diblo** [comment]
Haha I have found the solution through a piece of code. (Read the "Exception" message)

        if self._end_of_directory:
            raise Exception('Current XBMC handle has been removed. Either '
                            'set_resolved_url(), end_of_directory(), or '
                            'finish() has already been called.')

The solution is to call the method `xbmcplugin.endOfDirectory()` to remove the handle id.

        log("(Main) Creating player options")

        if settings.addon.handle > -1:
            xbmcplugin.endOfDirectory(settings.addon.handle, True, False, False)

        play3d = False

:palm_tree:

**Comment by chakhdin** [comment]
Yeap, works perfectly now.

**Comment by Diblo** [comment]
:+1:
