### ISSUE TITLE
File size vs available space

### ISSUE THREAD

**Issue by Diblo** [Diblo/KODI-Popcorn-Time#59]
@Chakhdin
I may have caused this error, but this will fail because the check are done after the space are pre-allocate. 
https://github.com/Diblo/KODI-Popcorn-Time/blob/master/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py#L311

**Comment by Diblo** [comment]
We can fix this by adding "size_bytes" in movie provider to the item information below properties.

I'm first home in two hours. Can you see if you can fix this? ☺

**Comment by chakhdin** [comment]
That would be a very clean solution. I was getting the file size from the torrent once the download has started, but if we can get the size_bytes directly from yts.to then we can check before starting torrent2http.
Anyway, I'm using this morning's version and I didn't have any problems with file size check.

**Comment by Diblo** [comment]
Are you sure!?!
Because I have just finished making changes :P 
.... However,

I have move the `_calculate_free_space()` to the `main.py` (in the `PopcornTime` class) and

    def player(self, subtitle=None, **params):
        log("(Main) Creating player options")
        params = dict((p, simplejson.loads(params[p])) for p in params) # temporary fix
        free_space = self._calculate_free_space()

        if settings.addon.handle > -1:
            xbmcplugin.endOfDirectory(settings.addon.handle, True, False, False)

        play3d = False
        if params.get('3D') and params['3D']['size'] < free_space and '3D' in self.mediaSettings.qualities:
            play3d = True
            if self.mediaSettings.play3d == 1:
                play3d = Dialog().yesno(30010, 30011)

        quality = None
        if play3d:
            quality = '3D'
        elif params.get('1080p') and params['1080p']['size'] < free_space and '1080p' in self.mediaSettings.qualities:
            quality = '1080p'
        elif params.get('720p') and params['720p']['size'] < free_space:
            quality = '720p'

        if not quality:
            notify(message=__addon__.getLocalizedString(30323) + self.mediaSettings.download_path, level=NOTIFYLEVEL.WARNING);
            log('(Main) Not enough space on filesystem. There must be a minimum of %s, %s available in %s' %(shortenBytes(params['720p']['size']), shortenBytes(free_space), self.mediaSettings.download_path))
            Abort()

        TorrentPlayer().playTorrentFile(self.mediaSettings, build_magnetFromMeta(params[quality]['hash'], "quality %s" %quality), self.getSelectedItem(), subtitle)

**Comment by Diblo** [comment]
Besides that there is a clean solution, but also it selects a lower quality if there is no space.
I had not foreseen this possibility and I think we should use it in place. What do you think?

**Comment by chakhdin** [comment]
Isn't it going to be messy? There's no space for a 3d 1080p version, but there is for a 2d 1080p or for a 3d 720p. What would you do? 
I guess that not having available space is not the normal situation: either the user forgot to choose the correct directory or he unexpectedly run out of space. We should warn the user to free up space and/or choose a different filesystem, or choose a lower resolution version. I'd concentrate on getting tv shows to work. Put this one in the wish-list.
Did you see my email with the vector based image?

Cheers

**Comment by Diblo** [comment]
I believe you're right. It gets a little messy if we just play a make quality without notifying the user about it. But what about informing the user while play continues with the quality there was space for? Or was that what you were thinking? :p 
It's alright. Shall I take care of the other things or do you need for my help to be finished.
Yes, i have just looked at :+1: I will update the icons soon.

However, I'm on vacation throughout next week, so you know why I'm gone :)

**Comment by Diblo** [comment]
@chakhdin 
https://github.com/Diblo/KODI-Popcorn-Time/wiki/Todo
