### ISSUE TITLE
why my KODI-Popcorn Time addon  is always 0.6.5

### ISSUE THREAD

**Issue by nxtreaming** [Diblo/KODI-Popcorn-Time#62]
I installed it from 1.04

How to update the latest version?

**Comment by chakhdin** [comment]
Hi @nxtreaming 
0.70 version is an Alpha 2 release and you have to install it manually. It will be available from the repository when it reaches the stable version.
Get the 0.70 Alpha 2 here https://github.com/Diblo/KODI-Popcorn-Time/wiki/Test-releases

**Comment by nxtreaming** [comment]
Get it.
Thanks
