### ISSUE TITLE
Playback does not start

### ISSUE THREAD

**Issue by nxtreaming** [Diblo/KODI-Popcorn-Time#71]
Ver: 0.70 alpha 2

log:
.......
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/status
10:10:02 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/status
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/status
10:10:02 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/ls
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/ls
10:10:02 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/status
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:02 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/ls
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/ls
10:10:03 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:03 T:5260    NONE:  NOTICE: [plugin.video.kodipopcorntime] (Torrent) IOError: [Errno 9] Bad file descriptor
10:10:03 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/ls
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/ls
10:10:03 T:5260    NONE:    INFO: [plugin.video.kodipopcorntime] (URL) Trying to obtaining data from http://127.0.0.1:5001/status
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Headers: {'Accept-Encoding': 'gzip', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.36'}
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (URL) Reading response
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Reading JSON data
10:10:03 T:5260    NONE:   DEBUG: [plugin.video.kodipopcorntime] (Json) Successful receive data from http://127.0.0.1:5001/status
......

However the download speed is normal

I can check the status by:
http://127.0.0.1:5001/status

The response:
{"name":"Terminator Genisys (2015) [1080p]","state":3,"state_str":"downloading","error":"","progress":0.0473,"download_rate":72.506836,"upload_rate":9.666016,"total_download":109623664,"total_upload":7483921,"num_peers":171,"num_seeds":151,"total_seeds":11563,"total_peers":7602}

------------------------------------
http://127.0.0.1:5001/ls

The response:
{"files":[{"name":"Terminator Genisys (2015) [1080p]\\Terminator.Genisys.2015.1080p.BluRay.x264.YIFY.mp4","save_path":"C:\\Users\\Administrator\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.kodipopcorntime\\cache\\movies\\Terminator Genisys (2015) [1080p]\\Terminator.Genisys.2015.1080p.BluRay.x264.YIFY.mp4","url":"http://127.0.0.1:5001/files/Terminator%20Genisys%20%282015%29%20%5B1080p%5D%5CTerminator.Genisys.2015.1080p.BluRay.x264.YIFY.mp4","size":1989549991,"offset":0,"download":93724583,"progress":0.047108434},{"name":"Terminator Genisys (2015) [1080p]\\WWW.YTS.TO.jpg","save_path":"C:\\Users\\Administrator\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.kodipopcorntime\\cache\\movies\\Terminator Genisys (2015) [1080p]\\WWW.YTS.TO.jpg","url":"http://127.0.0.1:5001/files/Terminator%20Genisys%20%282015%29%20%5B1080p%5D%5CWWW.YTS.TO.jpg","size":105983,"offset":1989549991,"download":105983,"progress":1}]}

------------------------------------
I can start 3rd player(such as VLC) by using the url [http://127.0.0.1:5001/files/Terminator%20Genisys%20%282015%29%20%5B1080p%5D%5CTerminator.Genisys.2015.1080p.BluRay.x264.YIFY.mp4] which is obtained from http://127.0.0.1:5001/ls

But KODI fails to launch the video playback windows.

**Comment by nxtreaming** [comment]
Update:

the playback is OK after the status: 
{"name":"Terminator Genisys (2015) [1080p]","state":3,"state_str":"downloading","error":"","progress":0.173669,"download_rate":154.48828,"upload_rate":9.017578,"total_download":383437477,"total_upload":56338300,"num_peers":178,"num_seeds":167,"total_seeds":11563,"total_peers":7602}

But I fail to load the subtitle.

**Comment by Diblo** [comment]
Can you post the full log file, where you have enable plugin and system debugging?

Greetings
Diblo

 \- [Easy Log file guide.](http://kodi.wiki/view/Log_file/Easy)
![kodi_popcorn_time_-_settings_advanced_1](https://cloud.githubusercontent.com/assets/11947723/10267480/c976e236-6a96-11e5-8611-5c068109dbae.jpg)

**Comment by Diblo** [comment]
At one point, our link to the Alpha release stopped to link to the latest reviewed zip file. As result we have to ask you to reinstall the the addon so we and you can get a properly test result.
https://drive.google.com/file/d/0B3fNnjj64nUpdnZXM2dYb05NUzg/view?usp=sharing

**Comment by nxtreaming** [comment]
@Diblo Thanks, I will try latest version.

**Comment by Diblo** [comment]
Hi @nxtreaming
Have this bug been solved?

Greetings,
Diblo

**Comment by nxtreaming** [comment]
@Diblo the bug has gone.

Thanks

**Comment by Diblo** [comment]
:+1:
