### ISSUE TITLE
strm file

### ISSUE THREAD

**Issue by thetruemachine** [Diblo/KODI-Popcorn-Time#75]
How i get the strm file for add it to my kodi library?

**Comment by Diblo** [comment]
You can change the download path to your movie library and enable "Keep files ...".

Version 0.6.5
![kodi_popcorn_time_-_general_settings 1](https://cloud.githubusercontent.com/assets/11947723/10426446/ab13d8ee-70e0-11e5-873c-05b271433ad6.jpg)

Version 0.7.0 Alpha 2
![kodi_popcorn_time_-_settings_movie_2 1](https://cloud.githubusercontent.com/assets/11947723/10426396/3bee81bc-70e0-11e5-8662-5d31a9780594.jpg)

**Comment by thetruemachine** [comment]
Thank, but no is exactly it that i want. I meant something like this: https://github.com/mancuniancol/script.yts2kd. But instead of Pulsar that it use  Kodi Popcorn, that is the best.

**Comment by Diblo** [comment]
Unfortunately this is not possible, but it seems to be a good idea. However, I can not promise it will be added as we work to get version 0.7.0 finished.

Greetings
Diablo

**Comment by thetruemachine** [comment]
Thank for you answer.
