### ISSUE TITLE
Error when trying to browse most popular

### ISSUE THREAD

**Issue by iancrowther** [Diblo/KODI-Popcorn-Time#82]
It appears not to be able to reach the short url.

I have enabled debugging if you need to me to output some log info?

**Comment by Frepke** [comment]
Hello iancrowther,

YTS (the movie source) shuts down 4ever: https://torrentfreak.com/yify-yts-shuts-down-the-end-of-a-piracy-icon-151030/

**Comment by iancrowther** [comment]
that'd do it.. ty
