### ISSUE TITLE
File does not have proper structure. Kodi 15.2. Archlinux ARMv7

### ISSUE THREAD

**Issue by GAZ082** [Diblo/KODI-Popcorn-Time#95]
Yep. I downloaded the file, hit install with zip, and get that error.

Help?

Thanks a happy new year!

**Comment by fibbers** [comment]
Make sure the file owner matches the user which runs Kodi. I had to do `chown kodi ....zip` to fix this.

**Comment by GAZ082** [comment]
That did the trick, thank you!
